// Generated by tools/export_slide_data.py — real OpenAI embeddings.
// Do not edit by hand.
window.RAG_DATA = {
 "retrieval": {
  "chunks": [
   "Annual leave. Every full time employee receives 25 days of annual leave per year, plus public holidays in the country where they are registered. Leave accrues monthly from the start date. You may carry a maximum of 5 unused days into the following year.\n\nEquipment and expenses. New joiners receive a laptop budget of",
   "New joiners receive a laptop budget of 2000 euros and a home office budget of 600 euros in their first month. Recurring costs such as internet and electricity are not reimbursed. Submit receipts within 30 days of purchase or the claim is rejected.\n\nDeadlines. We would rather hear about a slipping deadline three weeks",
   "about a slipping deadline three weeks early than three days early. Raise it in your team channel as soon as you know. A missed deadline is a planning problem, not a performance problem.\n\nPayroll. Payroll runs on the 25th of each month, or the last working day before it if the 25th falls on a weekend. For anything",
   "25th falls on a weekend. For anything related to pay, tax documents or your contract, contact the people operations team.\n\nReviews. Formal reviews happen twice a year, in June and December. Promotion decisions are made in the December cycle only. Salary adjustments take effect from the first of February."
  ],
  "presets": [
   "annual leave",
   "laptop budget",
   "when is payday",
   "what is the capital of France"
  ],
  "scores": {
   "annual leave": [
    0.6729,
    0.2574,
    0.2472,
    0.3327
   ],
   "laptop budget": [
    0.2441,
    0.4877,
    0.1389,
    0.1133
   ],
   "when is payday": [
    0.2154,
    0.2061,
    0.4968,
    0.4514
   ],
   "what is the capital of France": [
    0.0958,
    0.136,
    0.0494,
    0.0788
   ]
  }
 },
 "words": [
  "cat",
  "kitten",
  "dog",
  "puppy",
  "elephant",
  "lion",
  "apple",
  "mango",
  "banana",
  "coffee",
  "tea",
  "water"
 ],
 "groups": {
  "cat": "animals",
  "kitten": "animals",
  "dog": "animals",
  "puppy": "animals",
  "elephant": "animals",
  "lion": "animals",
  "apple": "fruit",
  "mango": "fruit",
  "banana": "fruit",
  "coffee": "drinks",
  "tea": "drinks",
  "water": "drinks"
 },
 "similarity": [
  [
   1.0,
   0.5697,
   0.6027,
   0.4115,
   0.319,
   0.507,
   0.3568,
   0.2636,
   0.2979,
   0.3847,
   0.358,
   0.3022
  ],
  [
   0.5697,
   1.0,
   0.4195,
   0.6498,
   0.2624,
   0.3736,
   0.2819,
   0.3009,
   0.2617,
   0.2914,
   0.3352,
   0.2482
  ],
  [
   0.6027,
   0.4195,
   1.0,
   0.559,
   0.3704,
   0.4924,
   0.3236,
   0.2642,
   0.2563,
   0.3514,
   0.2826,
   0.3339
  ],
  [
   0.4115,
   0.6498,
   0.559,
   1.0,
   0.3225,
   0.3509,
   0.3062,
   0.3345,
   0.2713,
   0.2867,
   0.2759,
   0.2575
  ],
  [
   0.319,
   0.2624,
   0.3704,
   0.3225,
   1.0,
   0.4646,
   0.2757,
   0.3534,
   0.2644,
   0.188,
   0.2606,
   0.2736
  ],
  [
   0.507,
   0.3736,
   0.4924,
   0.3509,
   0.4646,
   1.0,
   0.3612,
   0.3005,
   0.3535,
   0.2909,
   0.274,
   0.3183
  ],
  [
   0.3568,
   0.2819,
   0.3236,
   0.3062,
   0.2757,
   0.3612,
   1.0,
   0.3837,
   0.4636,
   0.3777,
   0.3591,
   0.3067
  ],
  [
   0.2636,
   0.3009,
   0.2642,
   0.3345,
   0.3534,
   0.3005,
   0.3837,
   1.0,
   0.4104,
   0.2974,
   0.2736,
   0.2613
  ],
  [
   0.2979,
   0.2617,
   0.2563,
   0.2713,
   0.2644,
   0.3535,
   0.4636,
   0.4104,
   1.0,
   0.3452,
   0.3629,
   0.271
  ],
  [
   0.3847,
   0.2914,
   0.3514,
   0.2867,
   0.188,
   0.2909,
   0.3777,
   0.2974,
   0.3452,
   1.0,
   0.6108,
   0.4163
  ],
  [
   0.358,
   0.3352,
   0.2826,
   0.2759,
   0.2606,
   0.274,
   0.3591,
   0.2736,
   0.3629,
   0.6108,
   1.0,
   0.3856
  ],
  [
   0.3022,
   0.2482,
   0.3339,
   0.2575,
   0.2736,
   0.3183,
   0.3067,
   0.2613,
   0.271,
   0.4163,
   0.3856,
   1.0
  ]
 ],
 "coords": [
  [
   -0.7378,
   0.4381
  ],
  [
   -0.9665,
   0.4693
  ],
  [
   -0.901,
   0.239
  ],
  [
   -1.0,
   0.2
  ],
  [
   -0.2749,
   -1.0
  ],
  [
   -0.4664,
   -0.4922
  ],
  [
   0.6375,
   -0.42
  ],
  [
   0.4278,
   -0.9455
  ],
  [
   0.8068,
   -0.6427
  ],
  [
   0.9238,
   0.9329
  ],
  [
   0.9365,
   0.8277
  ],
  [
   0.6141,
   0.3933
  ]
 ],
 "mismatch": {
  "question": "What were our sales in the first quarter?",
  "correct": "Q1 revenue reached 4.2 million dollars.",
  "right": [
   {
    "text": "Q1 revenue reached 4.2 million dollars.",
    "score": 0.5473
   },
   {
    "text": "Refunds are issued within 30 days of purchase.",
    "score": 0.1866
   },
   {
    "text": "Expense claims must be filed within 60 days.",
    "score": 0.1499
   },
   {
    "text": "Parking permits are renewed each January.",
    "score": 0.1386
   },
   {
    "text": "Guest wifi resets every Monday morning.",
    "score": 0.0545
   },
   {
    "text": "The office is closed on public holidays.",
    "score": 0.0448
   }
  ],
  "wrong": [
   {
    "text": "Q1 revenue reached 4.2 million dollars.",
    "score": 0.026
   },
   {
    "text": "The office is closed on public holidays.",
    "score": -0.0135
   },
   {
    "text": "Refunds are issued within 30 days of purchase.",
    "score": -0.018
   },
   {
    "text": "Expense claims must be filed within 60 days.",
    "score": -0.0308
   },
   {
    "text": "Guest wifi resets every Monday morning.",
    "score": -0.0355
   },
   {
    "text": "Parking permits are renewed each January.",
    "score": -0.0617
   }
  ]
 },
 "meta": {
  "model": "text-embedding-3-small",
  "dimensions": 1536,
  "wrongModel": "text-embedding-3-large @ 1536"
 }
};
