/* Build a minimal highlight.js for the deck.
 *
 *   npm pack highlight.js && tar xzf highlight.js-*.tgz     # gives ./package
 *   node tools/build_highlight.mjs ./package
 *
 * Reveal vendors the full highlight.js: 960KB to colour three languages, and
 * a second 960KB ESM copy that is never loaded. The deck only ever uses
 * python, bash and plaintext, so this bundles core plus those three.
 *
 * The lib/ files are CommonJS with no require() calls, so they can simply be
 * wrapped in a module shim and concatenated - no bundler needed.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC = process.argv[2];
if (!SRC) { console.error('usage: node tools/build_highlight.mjs <highlight.js package dir>'); process.exit(1); }

const LANGUAGES = ['python', 'bash', 'plaintext'];
const OUT = path.join(ROOT, 'slides', 'vendor', 'reveal', 'plugin', 'highlight', 'highlight.js');

const read = (p) => fs.readFileSync(path.join(SRC, p), 'utf8');
const wrap = (body, after) =>
  `(function(){var module={exports:{}};var exports=module.exports;\n${body}\n${after}})();\n`;

const version = JSON.parse(read('package.json')).version;
const PLUGIN_DIR = path.join(ROOT, 'slides', 'vendor', 'reveal', 'plugin', 'highlight');

// reveal's plugin.js is ESM: one import of hljs, one default export.
// Strip both and the remainder is a plain script body.
const pluginSrc = fs.readFileSync(path.join(PLUGIN_DIR, 'plugin.js'), 'utf8');
const exportLine = pluginSrc.match(/^export default (.+);\s*$/m);
if (!exportLine) throw new Error('could not find plugin.js default export');
const pluginBody = pluginSrc
  .replace(/^import hljs from 'highlight\.js';\s*/m, '')
  .replace(/^export default .+;\s*$/m, '');

const mod = (body, tail) =>
  `(function(){var module={exports:{}};var exports=module.exports;\n${body}\n${tail}})();\n`;

let out = `/* Minimal highlight build for this deck: highlight.js ${version} core plus\n` +
          `   ${LANGUAGES.join(', ')}, bundled with reveal's highlight plugin.\n` +
          `   Generated by tools/build_highlight.mjs - do not edit. */\n`;
out += '(function(){\n';
out += 'var hljs;\n';
out += mod(read('lib/core.js'), 'hljs = module.exports;');
for (const lang of LANGUAGES) {
  out += mod(read(`lib/languages/${lang}.js`),
             `hljs.registerLanguage(${JSON.stringify(lang)}, module.exports);`);
}
out += 'window.hljs = hljs;\n';
out += pluginBody + '\n';
out += `window.RevealHighlight = ${exportLine[1]};\n`;
out += '})();\n';

fs.writeFileSync(OUT, out);

const esm = path.join(PLUGIN_DIR, 'highlight.esm.js');
if (fs.existsSync(esm)) { fs.rmSync(esm); console.log('  removed unused highlight.esm.js'); }

console.log(`  wrote ${path.relative(ROOT, OUT)} — ${Math.round(out.length / 1024)} KB (was ~918 KB)`);
