#!/usr/bin/env python3
"""Precompute the real data the interactive slides need, into slides/data.js.

The interactive widgets run in a browser with no API key, so anything that
needs a real embedding has to be computed here, once, and shipped as data.
That keeps the honest parts honest: the word-similarity explorer and the
model-mismatch toggle both show genuine OpenAI numbers, not a simulation.

    demo/venv/bin/python tools/export_slide_data.py

Uses the same on-disk embedding cache as the demos, so re-running is free.
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "demo"))

from _demo import CachedEmbeddings, cosine  # noqa: E402

OUT = ROOT / "slides" / "data.js"

WORDS = [
    "cat", "kitten", "dog", "puppy", "elephant", "lion",
    "apple", "mango", "banana",
    "coffee", "tea", "water",
]
GROUPS = {
    "cat": "animals", "kitten": "animals", "dog": "animals",
    "puppy": "animals", "elephant": "animals", "lion": "animals",
    "apple": "fruit", "mango": "fruit", "banana": "fruit",
    "coffee": "drinks", "tea": "drinks", "water": "drinks",
}

# The mismatch demo, reduced to the two rankings the slide toggles between.
FACTS = [
    "Refunds are issued within 30 days of purchase.",
    "Q1 revenue reached 4.2 million dollars.",
    "Guest wifi resets every Monday morning.",
    "The office is closed on public holidays.",
    "Parking permits are renewed each January.",
    "Expense claims must be filed within 60 days.",
]
MISMATCH_Q = "What were our sales in the first quarter?"


def pca2(vectors):
    """Project to two dimensions with a tiny power-iteration PCA (no scipy)."""
    import numpy as np
    m = np.array(vectors, dtype=float)
    m = m - m.mean(axis=0)
    # top-2 right singular vectors
    _, _, vt = np.linalg.svd(m, full_matrices=False)
    coords = m @ vt[:2].T
    # normalise into a friendly -1..1 box
    span = np.abs(coords).max(axis=0)
    span[span == 0] = 1
    return (coords / span).tolist()


def main():
    small = CachedEmbeddings(model="text-embedding-3-small", quiet=True)

    print("embedding words ...")
    wv = small.embed_documents(WORDS)
    sim = [[round(cosine(a, b), 4) for b in wv] for a in wv]
    coords = [[round(x, 4), round(y, 4)] for x, y in pca2(wv)]

    print("embedding mismatch facts ...")
    fact_v = small.embed_documents(FACTS)
    large = CachedEmbeddings(model="text-embedding-3-large",
                             dimensions=1536, quiet=True)

    def rank(query_vec):
        scored = [(FACTS[i], round(cosine(query_vec, fv), 4))
                  for i, fv in enumerate(fact_v)]
        return sorted(scored, key=lambda p: -p[1])

    right = rank(small.embed_query(MISMATCH_Q))
    wrong = rank(large.embed_query(MISMATCH_Q))

    data = {
        "words": WORDS,
        "groups": GROUPS,
        "similarity": sim,
        "coords": coords,
        "mismatch": {
            "question": MISMATCH_Q,
            "correct": "Q1 revenue reached 4.2 million dollars.",
            "right": [{"text": t, "score": s} for t, s in right],
            "wrong": [{"text": t, "score": s} for t, s in wrong],
        },
        "meta": {
            "model": "text-embedding-3-small",
            "dimensions": 1536,
            "wrongModel": "text-embedding-3-large @ 1536",
        },
    }

    OUT.write_text(
        "// Generated by tools/export_slide_data.py — real OpenAI embeddings.\n"
        "// Do not edit by hand.\n"
        "window.RAG_DATA = " + json.dumps(data, indent=1) + ";\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT.relative_to(ROOT)}  ({OUT.stat().st_size:,} bytes)")
    print(f"  right-model top hit: {right[0][0][:44]!r} {right[0][1]}")
    print(f"  wrong-model top hit: {wrong[0][0][:44]!r} {wrong[0][1]}")


if __name__ == "__main__":
    main()
